export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_IN_RECIEVE = 'USER_LOGGED_IN_RECIEVE';
export const ERROR_REQUESTS = 'ERROR_REQUESTS';
export const SUCCESS_REQUESTS = 'SUCCESS_REQUESTS';
